daemon_name = 'cli-template-service'
log_level = 'INFO'
[http]
enable = true
port = 80

[https]
enable = true
port = 443
crt_path = 'assets/cert/crt.crt'
key_path = 'assets/cert/key.key'
html_dir = 'assets/html'

[auto_cert]
enable = false
check_interval = 3600
crt_path = ''
init_download = true
key_path = ''
url = ''

[api]
doc_gen_search_dir = 'cmd/default_/http/api'
doc_gen_mainfile = 'api.go'
doc_gen_output_dir = 'cmd/default_/http/api_docs'

[redis]
enable = false
use_tls = true
host = 'localhost'
port = 6379
username = 'xxxx'
password = 'xxxx'
prefix = 'template'

[db]
enable = false
host = 'localhost'
port = 3306
name = 'xxxx'
username = 'xxxx'
password = 'xxxx'

[elasticsearch]
enable = false
host = 'localhost'
username = 'xxxx'
password = 'xxxx'

[ip_local]
enable = false
db_path = 'assets/ip2l/IP2LOCATION-LITE-DB1.BIN'
upgrade_interval = 172800
upgrade_url = ''

[ip_remote]
enable = false
ipstack_key = ''

[ip_remote.redis]
host = 'localhost'
port = 6379
prefix = 'core:ipgeo:'
username = ''
password = ''
use_tls = false


[leveldb]
enable = false
path = ''

[smtp]
enable = false
host = ''
port = 587
password = ''
username = ''

[sqlite]
enable = false
path = ''

